### ISSUE TITLE
Update databaseRefreshDdev() to be able to be run from within the local dev container

### ISSUE THREAD

**Issue by markdorison** [ChromaticHQ/chq-robo#80] opened 2022-07-05 15:13 UTC
## Description

[`databaseRefreshDdev()`](https://github.com/ChromaticHQ/usher/blob/e24704a2b41ab2b064e89d352e9f0294eada8ee6/src/Robo/Plugin/Commands/DevelopmentModeBaseCommands.php#L62-L71) must be run from outside ddev since we [currently use the DDEV`db-import` command](https://github.com/ChromaticHQ/usher/blob/e24704a2b41ab2b064e89d352e9f0294eada8ee6/src/Robo/Plugin/Commands/DevelopmentModeBaseCommands.php#L81-L82) to handle the import. `robo dev:refresh` also uses this method so currently we are forced to run this from outside the container which means dependencies like PHP must be installed locally.

## Proposed Solution

Refactor `databaseRefreshDdev()` to be able to run from inside the ddev container.

## Additional Context

@goranmiric mentioned on a back-end call that he

**Comment by apotek** [comment] 2023-08-16 17:35
I just wanted to note that I run my db refreshes from within Lando all the time by 1) making sure the Lando appserver image has the AWS cli installed and 2) configurating AWS environment variables in .lando/env (and setting the `environment` key in the Lando config to use that file).

**Comment by markdorison** [comment] 2023-08-16 21:14
@apotek I am not sure I follow. What is the next step to refresh the db this way? How do you trigger it?

Side note: I should probably rename this issue to refer to DDEV, but I didn't want to cause any confusion so I held off for now.

**Comment by apotek** [comment] 2024-07-18 18:31
Removed references to Lando. We are no longer using Lando. The issue is updated to refer to ddev now.

**Comment by apotek** [comment] 2024-09-12 17:04
Gah. This is basically a duplicate of #204.

**Closed as completed by apotek** 2024-09-12 17:04 UTC
Labels: enhancement
